export const TABLE_INFO = [
  {
    DATE: "10.12.2023",
    CITY: "Montreal, QC",
    VENUE: "Beanfield Theatre",
    SUPPORTING_ACT: "Emile Cristensen",
  },
  {
    DATE: "10.13.2023",
    CITY: "Toronto, ON",
    VENUE: "Toronto Concert Hall",
    SUPPORTING_ACT: "Emile Cristensen, Halya",
  },
  {
    DATE: "10.15.2023",
    CITY: "Chicago, IL",
    VENUE: "Vic Theatre",
    SUPPORTING_ACT: "Tom Glasser",
  },
  {
    DATE: "10.16.2023",
    CITY: "Philadelphia, PA",
    VENUE: "Kimmel Auditorium",
    SUPPORTING_ACT: "Tom Glasser, Grivax",
  },
  {
    DATE: "10.17.2023",
    CITY: "Brooklyn, NY",
    VENUE: "King’s Theatre",
    SUPPORTING_ACT: "Tom Glasser, Grivax",
  },
  {
    DATE: "10.18.2023",
    CITY: "Brooklyn, NY",
    VENUE: "King’s Theatre",
    SUPPORTING_ACT: "Tom Glasser, Grivax",
  },
  {
    DATE: "10.20.2023",
    CITY: "Boston, MA",
    VENUE: "Emerson Colonial Theatre",
    SUPPORTING_ACT: "Tom Glasser, Grivax",
  },
  {
    DATE: "10.21.2023",
    CITY: "Washington, DC",
    VENUE: "Gala Theatre",
    SUPPORTING_ACT: "Grivax, Clarence Too",
  },
  {
    DATE: "10.22.2023",
    CITY: "Wilmington, NC",
    VENUE: "Wilmington Theatre",
    SUPPORTING_ACT: "Grivax, Clarence Too",
  },
  {
    DATE: "10.23.2023",
    CITY: "Miami, FL",
    VENUE: "Olympia Theatre",
    SUPPORTING_ACT: "Grivax, Clarence Too",
  },
  {
    DATE: "10.26.2023",
    CITY: "Manchester, UK",
    VENUE: "Albert Hall",
    SUPPORTING_ACT: "Harvey Carls, Mortales",
  },
  {
    DATE: "11.2.2023",
    CITY: "Brussels, BE",
    VENUE: "Botanique Auditorium",
    SUPPORTING_ACT: "Panora, Matechre",
  },
  {
    DATE: "11.3.2023",
    CITY: "Zurich, CH",
    VENUE: "Hellenic Theatre",
    SUPPORTING_ACT: "Panora, Matechre",
  },
  {
    DATE: "11.4.2023",
    CITY: "Cavallo, IT",
    VENUE: "Cavallo Festival",
    SUPPORTING_ACT: "Festival Acts",
  },
  {
    DATE: "11.5.2023",
    CITY: "St. Malo, FR",
    VENUE: "Immersion Festival",
    SUPPORTING_ACT: "Festival Acts",
  },
  {
    DATE: "11.12.2023",
    CITY: "Paris, FR",
    VENUE: "Mogador Theatre",
    SUPPORTING_ACT: "Carly Stuart, Tokena ",
  },
  {
    DATE: "11.13.2023",
    CITY: "Berlin, DE",
    VENUE: "Stage Theatre",
    SUPPORTING_ACT: "Carly Stuart, Tokena ",
  },
];
